name: Glance
options:
  bundleIdPrefix: com.glance
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  Glance:
    type: application
    platform: macOS
    sources:
      - path: Glance
        excludes:
          - Assets.xcassets/AppIcon.appiconset/*.png
    postBuildScripts:
      - name: Copy UI Resources
        script: |
          UI_SRC="${SRCROOT}/../ui"
          UI_DST="${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/ui"
          mkdir -p "${UI_DST}"
          cp -R "${UI_SRC}/"* "${UI_DST}/"
        basedOnDependencyAnalysis: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.glance.app
        PRODUCT_NAME: Glance
        INFOPLIST_FILE: Glance/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        ENABLE_HARDENED_RUNTIME: YES
      configs:
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -Owholemodule
